sudo: false
language: python
cache: pip

python:
  - "3.8"

before_install:
  - stty cols 80

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install codecov --dev

script:
  - pipenv run flake8
  - pipenv run pytest

after_success: pipenv run codecov
