version: 1.0.{build}

# Turn off default msbuild integration
build: false

init:
  - ps: ls -Name "c:\\python*"
  - "SET PATH=\\Python36;\\Python36\\Scripts;%PATH%"

install:
  - ps: ls -name "C:\\Python36\\Lib\\site-packages"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade pip"
  - "pip --version"
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - "pip install pipenv"
  - "python -m venv .venv"
  - ps: .venv\Scripts\activate.ps1
  - "pipenv install --dev"
  - "pip freeze"
  - "pipenv run flake8"
  - "pipenv run setup.py build"

test_script:
  - cd /D %APPVEYOR_BUILD_FOLDER%
  - pipenv run pytest --version
  - pipenv run pytest
