site_name: Habito

repo_name: codito/habito
repo_url: https://github.com/codito/habito

nav:
  - Overview: 'index.md'
  - Commands: 'commands.md'
  - License: 'license.md'

theme:
  name: "material"
  palette:
    primary: 'light blue'
    accent: 'deep orange'
